### ISSUE TITLE
3.3v to 5v level translation

### ISSUE THREAD

**Issue by 123swk123** [katsuster/target-6-board#1]
Here is my recommendation for the voltage level translation this will improve the slew rate

for frequency range 100KHz ~ 1MHz and for short wiring length
![image](https://github.com/katsuster/target-6-board/assets/903389/7d6ee366-5d5d-4a88-8ccd-9d11a57cc936)

frequency range > 1MHz and for long wiring length
![image](https://github.com/katsuster/target-6-board/assets/903389/aab62386-e0b9-4f8a-8714-a5fe2627ff55)

**Comment by 123swk123** [comment]
refer the blow picture, in PCB Gate and Source pins are swapped

bottom left corner is BSS138 spec

![image](https://github.com/katsuster/target-6-board/assets/903389/9f6785b5-2e44-4cb9-a364-6db717daab74)

**Comment by katsuster** [comment]
Thanks, fix the mistakes of PCB design in this commit.
https://github.com/katsuster/target-6-board/commit/ab95173e5db8b9afef80bbd365d9a09157b9c615

**Comment by katsuster** [comment]
And keep current bidirectional level-shift circuit for future changes.
Thanks for your comment!
